#base image
FROM ubuntu:18.04

#author info
MAINTAINER wangdamingll "wangdamingll@163.com"

#env set
ENV APPLICATION_NAME baseenv
ENV ENVIRONMENT development

#label set
LABEL Version="0.0.1" 

#add files to image
#ADD software.lic /opt/application/software.lic
#if you are in china,do follow below,otherwise,not do it
RUN ["cp", "/etc/apt/sources.list", "/etc/apt/sources.list_bak"]
ADD sources.list /etc/apt/ 

#flush apt cache
ENV REFRESHED_AT 2020-11-11
RUN ["apt-get", "update"] 　

#build args 
#ARG build
#ARG webapp_user=user

#set running container workdir
#WORKDIR /opt/test

#use what for running container
#USER root

#add image volume
#VOLUME ["/opt/project", "/data"]

#copy files to image
#COPY conf.d/ /etc/apache2/

#send signal for stoping container
#STOPSIGNAL

#use this image trigger
#ONBUILD ADD . /app/src
#ONBUILD RUN cd /app/src && make
ONBUILD RUN ["echo", "use base image env"] 　

# base image env set
RUN ["apt-get", "install","-y","vim","gcc","g++","gdb","cmake"] 　

#docker run cmd
ENTRYPOINT ["/bin/bash"]　
#CMD ["/bin/bash"]

